project:
  type: website
  output-dir: docs  # Required for GitHub Pages

website:
  title: "Abdul Zarbi"
  description: "Data Analyst & Researcher Portfolio"
  favicon: images/Abdul.png
  
  
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About Me"
        href: about.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Research"
        href: research.qmd
      - text: "Contact"
        href: contact.qmd
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/abdulzarbi
      - icon: github
        href: https://github.com/AbdulZarbi

  page-footer:
    left: "Â© 2025 Abdul Zarbi. All rights reserved."
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/abdulzarbi
      - icon: github
        href: https://github.com/AbdulZarbi

format:
  html:
    theme: 
      light: [cosmo, styles.css]
    css: styles.css
    toc: true
    toc-depth: 3
    code-copy: true
    code-fold: true
    link-external-newwindow: true